name: Cypress Tests - API Trello

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      trello_key: ${{ secrets.TRELLO_KEY }}
      trello_token: ${{ secrets.TRELLO_TOKEN }}

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes Cypress
        run: npx cypress run
